const fs=require('fs'),vm=require('vm'),path=require('path');
const base='https://ousiadesign.ch',root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s)};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const data={};for(const lang of ['en','de']){const w={};vm.runInNewContext(read('assets/projects-data'+(lang==='de'?'-de':'')+'.js'),{window:w});data[lang]=w[lang==='de'?'OUSIA_PROJECTS_DE':'OUSIA_PROJECTS'];}
const schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':base+'/#studio',name:'Ousia Design',url:base+'/',email:'info@ousiadesign.ch',logo:base+'/favicon.png',founder:{'@id':base+'/#daniel'}},{'@type':'Person','@id':base+'/#daniel',name:'Daniel Stofner',jobTitle:'Freelance Interior Designer',url:base+'/profile/',sameAs:['https://www.linkedin.com/in/daniel-stofner-4b838a127'],knowsLanguage:['German','Italian','English']}]};
function meta(h,title,desc,url,en,de,img='bar.webp'){
h=h.replace(/<link rel="alternate" hreflang="[^"]*"[^>]*>/g,'').replace(/<meta property="og:[^"]*"[^>]*>/g,'').replace(/<meta name="twitter:[^"]*"[^>]*>/g,'').replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,'');
h=h.replace(/<title>[\s\S]*?<\/title>/,'<title>'+esc(title)+'</title>').replace(/<meta name="description"[^>]*>/g,'').replace(/<link rel="canonical"[^>]*>/g,'');
return h.replace('</head>',`<meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="${en}"><link rel="alternate" hreflang="de" href="${de}"><link rel="alternate" hreflang="x-default" href="${en}"><meta property="og:type" content="website"><meta property="og:site_name" content="Ousia Design"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${base}/assets/images/${img}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(schema)}</script></head>`);
}
function render(lang,slug){const list={innerHTML:''},detail={innerHTML:''};const document={scripts:[],body:{dataset:{projectSlug:slug}},querySelector:s=>s==='link[data-project-ui]'?{}:s==='[data-project-list]'&&!slug?list:s==='[data-project-detail]'&&slug?detail:null,querySelectorAll:()=>[],title:''};vm.runInNewContext(read('assets/site'+(lang==='de'?'-de':'')+'.js'),{window:{OUSIA_PROJECTS:data.en,OUSIA_PROJECTS_DE:data.de},document,location:{search:'',pathname:(lang==='de'?'/de':'')+(slug?'/projects/'+slug+'/':'/')},URLSearchParams});return slug?detail.innerHTML:list.innerHTML;}
const urls=[],changed=[];function save(p,s){write(p,s);changed.push(p)}
for(const lang of ['en','de']){const de=lang==='de',pre=de?'de/':'';
for(const page of ['','profile/','contact/']){const p=pre+page+'index.html';let h=read(p),title,desc;
if(!page){title=de?'Freelance Interior Design & 3D-Rendering | Ousia Design':'Freelance Interior Designer & 3D Rendering | Ousia Design';desc=de?'Daniel Stofner: freie Mitarbeit in der Innenarchitektur, Interior Design und 3D-Visualisierung. Remote für Studios, Hotels und Privatkunden.':'Daniel Stofner: freelance interior designer for studios, hospitality and residential projects. Interior concepts, 3D rendering and remote design support.';
h=h.replace('FOUNDER OF OUSIA DESIGN · FOUNDER OF OUSIA LOOP · PARTNER AT STOFNER INTERIOR DESIGN','DANIEL STOFNER · FREELANCE INTERIOR DESIGN');
h=h.replace(/<p class="hero-lead">[\s\S]*?<\/p>/,de?'<p class="hero-lead">Interior Design, 3D-Visualisierung und freie Mitarbeit für Studios, Hotels und private Wohnprojekte.</p>':'<p class="hero-lead">Freelance interior design, 3D rendering and project support for studios, hospitality and residential spaces.</p>');
h=h.replace(/<section class="projects" data-project-list>[\s\S]*?<\/section>/,'<section class="projects" data-project-list>'+render(lang).replace(/href="project\/\?p=([^"]+)"/g,'href="projects/$1/"')+'</section>');
h=h.replace(de?'Ich arbeite projektbasiert mit privaten Auftraggebern, Interior-Studios, Architekten, Entwicklern und Hospitality-Teams zusammen.':'I collaborate with private clients, interior studios, architects, developers and hospitality teams on a flexible project basis.',de?'Ich unterstütze Architektur- und Interior-Studios in freier Mitarbeit: mit Raumplanung, Materialkonzepten, individuellen Möbeln und fotorealistischen 3D-Renderings. Privatkunden und Hospitality-Teams begleite ich projektbezogen vom Konzept bis zur weiteren Ausarbeitung.':'As a freelance interior designer, I support architecture and interior studios with space planning, material concepts, bespoke furniture and photorealistic 3D renderings. I also work with private clients and hospitality teams from concept through design development.');
h=h.replace(de?'Die Unterstützung kann von Konzeptentwicklung und räumlicher Direction bis zu Visualisierung, Maßmöbeln, Design Development und Projektkoordination reichen.':'Support can range from concept development and spatial direction to visualization, custom furniture, design development and project coordination.',de?'Von Italien aus biete ich Remote-Zusammenarbeit an – auch für Projekte in Zürich, Winterthur, Bozen, München und New York. Vor-Ort-Termine und Projektleitung im Innenausbau sind nach Vereinbarung und abhängig vom Projektumfang möglich.':'Based in Italy, I offer remote collaboration for projects in Zurich, Winterthur, Bolzano, Munich, New York and beyond. On-site visits and interior project coordination can be arranged according to the scope and location.');
}else if(page==='profile/'){title='Daniel Stofner – Freelance Interior Designer | Ousia Design';desc=de?'Daniel Stofner verbindet Interior Design, 3D-Visualisierung, Möbelentwurf und Projektkoordination. Wohn- und Hospitality-Projekte in Italien und der Schweiz.':'Meet Daniel Stofner: freelance interior designer combining concepts, 3D visualization, bespoke furniture and project coordination in Italy and Switzerland.';
}else{title=de?'Kontakt – Interior Design & freie Mitarbeit | Ousia Design':'Contact – Freelance Interior Design | Ousia Design';desc=de?'Interior Design, 3D-Renderings oder freie Mitarbeit anfragen: info@ousiadesign.ch. Remote-Zusammenarbeit und Vor-Ort-Termine nach Vereinbarung.':'Discuss interior design, 3D rendering or freelance studio support with Daniel Stofner. Contact info@ousiadesign.ch for remote collaboration.';}
const url=base+'/'+pre+page;save(p,meta(h,title,desc,url,base+'/'+page,base+'/de/'+page));urls.push(url);}
for(const p of data[lang]){const file=pre+'projects/'+p.slug+'/index.html';let h=read(file).replace(/<main data-project-detail>[\s\S]*?<\/main>/,'<main data-project-detail>'+render(lang,p.slug)+'</main>');h=h.replace(/<link[^>]*data-project-ui[^>]*>/g,'');h=h.replace('</head>','<link rel="stylesheet" data-project-ui href="/assets/project-content.css?v=20260917"></head>');const url=base+'/'+pre+'projects/'+p.slug+'/';save(file,meta(h,p.title+' | Ousia Design',p.description.slice(0,157)+(p.description.length>157?'…':''),url,base+'/projects/'+p.slug+'/',base+'/de/projects/'+p.slug+'/',p.cover));urls.push(url);}}
function walk(dir){return fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(dir+e.name+'/'):[dir+e.name]);}
for(const p of [...walk('ousia_portfolio_site/').filter(p=>p.endsWith('.html')),'manage/index.html','404.html'])save(p,read(p).replace(/<meta name="robots"[^>]*>/g,'').replace('</head>','<meta name="robots" content="noindex,follow"></head>'));
for(const p of ['about/index.html','de/about/index.html'])save(p,read(p).replace(/href="\.\.\/profile\/"/,'href="'+base+(p.startsWith('de/')?'/de':'')+'/profile/"'));
save('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+base+'/sitemap.xml\n');
save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'<url><loc>'+u+'</loc></url>').join('\n')+'\n</urlset>\n');
// Keep existing query-string project links compatible while identifying the static canonical.
for(const lang of ['en','de']){const pre=lang==='de'?'de/':'';const p=pre+'project/index.html';let h=read(p).replace(/<script data-project-redirect>[\s\S]*?<\/script>/g,'');const slugs=data[lang].map(p=>p.slug);const script=`<script data-project-redirect>(()=>{const slug=new URLSearchParams(location.search).get('p');if(${JSON.stringify(slugs)}.includes(slug)){location.replace('/${pre}projects/'+encodeURIComponent(slug)+'/'+location.hash);}})();</script>`;save(p,h.replace('</head>',script+'</head>'));}
if(process.env.SEO_MANIFEST)fs.writeFileSync(process.env.SEO_MANIFEST,JSON.stringify(changed));console.log(JSON.stringify({files:changed.length,sitemap:urls.length}));
